// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbawuozvprmnrgzvsari.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiYXd1b3p2cHJtbnJnenZzYXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzE2ODIsImV4cCI6MjA2NTMwNzY4Mn0.JWxZIJFtRVCkkBmdB5BMndQgY6GgZVND5cKXvi9U2qA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);